# Generated by Django 3.1.3 on 2021-01-26 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190402_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclepost',
            old_name='make',
            new_name='brand',
        ),
    ]
