# Generated by Django 3.1.3 on 2021-01-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210126_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_vehicule', models.TextField()),
                ('annee_vehicule', models.IntegerField()),
                ('couleur_vehicule', models.TextField(max_length=100)),
                ('etat_vehicule', models.TextField(max_length=100)),
                ('marque_vehicule', models.TextField(max_length=100)),
                ('modele_vehicule', models.TextField(max_length=100)),
                ('compteur_vehicule', models.IntegerField()),
                ('prix_vehicule', models.IntegerField()),
                ('description_vehicule', models.TextField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='BuyVehicle',
        ),
        migrations.DeleteModel(
            name='VehiclePost',
        ),
    ]
