# Generated by Django 3.1.3 on 2021-01-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210127_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicules',
            old_name='image_vehicule',
            new_name='quantite_vehicule',
        ),
        migrations.AddField(
            model_name='vehicules',
            name='image10_vehicule',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicules',
            name='image1_vehicule',
            field=models.ImageField(default=' ', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicules',
            name='image2_vehicule',
            field=models.ImageField(default='edan', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicules',
            name='image3_vehicule',
            field=models.ImageField(default='edan', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicules',
            name='image4_vehicule',
            field=models.ImageField(default='edan', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicules',
            name='image5_vehicule',
            field=models.ImageField(default='edan', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicules',
            name='image6_vehicule',
            field=models.ImageField(default='edan', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicules',
            name='image7_vehicule',
            field=models.ImageField(default='edan', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicules',
            name='image8_vehicule',
            field=models.ImageField(default='edan', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicules',
            name='image9_vehicule',
            field=models.ImageField(default='edan', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicules',
            name='vendu',
            field=models.CharField(default='edan', max_length=100),
            preserve_default=False,
        ),
    ]
