# Generated by Django 3.1.3 on 2021-01-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210128_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicules',
            name='image10_vehicule',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='image1_vehicule',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='image2_vehicule',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='image3_vehicule',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='image4_vehicule',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='image5_vehicule',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='image6_vehicule',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='image7_vehicule',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='image8_vehicule',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='image9_vehicule',
            field=models.ImageField(upload_to=''),
        ),
    ]
