# Generated by Django 3.1 on 2021-01-30 07:24

import app.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210128_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicules',
            name='date',
            field=models.CharField(default='30/1/2021', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='carburant_vehicule',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='couleur_vehicule',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='description_vehicule',
            field=models.TextField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='image10_vehicule',
            field=models.ImageField(default=' ', storage=app.storage.OverwriteStorage(), upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='image1_vehicule',
            field=models.ImageField(default=' ', storage=app.storage.OverwriteStorage(), upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='image2_vehicule',
            field=models.ImageField(default=' ', storage=app.storage.OverwriteStorage(), upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='image3_vehicule',
            field=models.ImageField(default=' ', storage=app.storage.OverwriteStorage(), upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='image4_vehicule',
            field=models.ImageField(default=' ', storage=app.storage.OverwriteStorage(), upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='image5_vehicule',
            field=models.ImageField(default=' ', storage=app.storage.OverwriteStorage(), upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='image6_vehicule',
            field=models.ImageField(default=' ', storage=app.storage.OverwriteStorage(), upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='image7_vehicule',
            field=models.ImageField(default=' ', storage=app.storage.OverwriteStorage(), upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='image8_vehicule',
            field=models.ImageField(default=' ', storage=app.storage.OverwriteStorage(), upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='image9_vehicule',
            field=models.ImageField(default=' ', storage=app.storage.OverwriteStorage(), upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='marque_vehicule',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='modele_vehicule',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='prix_vehicule',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='transmission_vehicule',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
