# Generated by Django 3.1 on 2021-01-31 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210130_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicules',
            name='date',
            field=models.CharField(default='31/1/2021', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='marque_vehicule',
            field=models.CharField(choices=[('Acura', 'Acura'), ('Audi', 'Audi'), ('Bentley', 'Bentley'), ('Bmw', 'Bmw'), ('Bugatti', 'Bugatti'), ('Buick', 'Buick'), ('Cadillac', 'Cadillac'), ('Chevy', 'Chevy'), ('Chrystler', 'Chrystler'), ('Dodge', 'Dodge'), ('Ferrari', 'Ferrari'), ('Fiat', 'Fiat'), ('Ford', 'Ford'), ('GMC', 'GMC'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('Infiniti', 'Infiniti'), ('Jaguar', 'Jaguar'), ('Jeep', 'Jeep'), ('Lamboghini', 'Lamboghini'), ('Land Rover', 'Land Rover'), ('Lexus', 'Lexus'), ('Maserati', 'Maserati'), ('Mazda', 'Mazda'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Nissan', 'Nissan'), ('Porsche', 'Porsche'), ('Rolls Royce', 'Rolls Royce'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo')], max_length=100),
        ),
    ]
