# Generated by Django 3.1 on 2021-01-31 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20210131_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicules',
            name='carburant_vehicule',
            field=models.CharField(blank=True, choices=[('ELECTRIQUE', 'ELECTRIQUE'), ('ESSENCE', 'ESSENCE'), ('DIESEL', 'DIESEL'), ('HYBRIDE', 'HYBRIDE')], max_length=100),
        ),
    ]
