# Generated by Django 3.1 on 2021-01-31 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210131_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicules',
            name='marque_vehicule',
            field=models.CharField(blank=True, choices=[('ACURA', 'ACURA'), ('ALPHA-ROMEO', 'ALPHA-ROMEO'), ('ALVIS', 'ALVIS'), ('ASTON-MARTIN', 'ASTON-MARTIN'), ('AUDI', 'AUDI'), ('BENTLEY', 'BENTLEY'), ('BMW', 'BMW'), ('BUGATTI', 'BUGATTI'), ('BUICK', 'BUICK'), ('CADILLAC', 'CADILLAC'), ('CHEVY', 'CHEVY'), ('CHRYSLER', 'CHRYSLER'), ('CITROËN', 'CITROËN'), ('DODGE', 'DODGE'), ('DS', 'DS'), ('EAGLE', 'EAGLE'), ('FERRARI', 'FERRARI'), ('FIAT', 'FIAT'), ('FORD', 'FORD'), ('GMC', 'GMC'), ('HONDA', 'HONDA'), ('HUMMER', 'HUMMER'), ('HYUNDAI', 'HYUNDAI'), ('INFINITI', 'INFINITI'), ('ISUZU', 'ISUZU'), ('JAGUAR', 'JAGUAR'), ('JEEP', 'JEEP'), ('KIA', 'KIA'), ('KTM', 'KTM'), ('LAMBORGHINI', 'LAMBORGHINI'), ('LAND-ROVER', 'LAND-ROVER'), ('LEXUS', 'LEXUS'), ('LOTUS', 'LOTUS'), ('MASERATI', 'MASERATI'), ('MAZDA', 'MAZDA'), ('MCLAREN', 'MCLAREN'), ('MERCEDES-BENZ', 'MERCEDES-BENZ'), ('MINI', 'MINI'), ('MITSUBISHI', 'MITSUBISHI'), ('NISSAN', 'NISSAN'), ('OPEL', 'OPEL'), ('PAGANI', 'PAGANI'), ('PEUGEOT', 'PEUGEOT'), ('PORSCHE', 'PORSCHE'), ('ROLLS-ROYCE', 'ROLLS-ROYCE'), ('SUBARU', 'SUBARU'), ('SUZUKI', 'SUZUKI'), ('TESLA', 'TESLA'), ('TOYOTA', 'TOYOTA'), ('VOLKSWAGEN', 'VOLKSWAGEN'), ('VOLVO', 'VOLVO'), ('WEBER', 'WEBER'), ('WIESMANN', 'WIESMANN'), ('ZASTAVA', 'ZASTAVA'), ('ZENVO', 'ZENVO')], max_length=100),
        ),
    ]
