# Generated by Django 3.1 on 2021-02-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20210201_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicules',
            name='date',
            field=models.CharField(blank=True, default='2/2/2021', max_length=100),
        ),
    ]
