# Generated by Django 3.1.6 on 2021-02-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20210204_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicules',
            name='carburant_vehicule',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('ELECTRIQUE', 'ELECTRIQUE'), ('ESSENCE', 'ESSENCE'), ('DIESEL', 'DIESEL'), ('HYBRIDE', 'HYBRIDE')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='date',
            field=models.CharField(blank=True, default='5/2/2021', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='etat_vehicule',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('NEUF', 'NEUF'), ('SECONDE-MAIN', 'SECONDE-MAIN')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='transmission_vehicule',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('AUTOMATIQUE', 'AUTOMATIQUE'), ('MANUELLE', 'MANUELLE'), ('MIXTE', 'MIXTE')], max_length=100),
        ),
    ]
