# Generated by Django 3.1.6 on 2021-02-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20210205_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicules',
            name='date',
            field=models.CharField(blank=True, default='6/2/2021', max_length=100),
        ),
    ]
