# Generated by Django 3.1.6 on 2021-02-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20210206_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicules',
            name='date',
            field=models.CharField(blank=True, default='7/2/2021', max_length=100),
        ),
    ]
